import type { SupportArticleMeta } from '@/types/support'

export const ARTICLES: SupportArticleMeta[] = [
  { slug: 'privacy-policy-explained', category: 'legal-privacy-and-compliance', title: 'Our Privacy Policy — plain language summary', description: 'A plain-language summary of what data DOT Mobile collects, how we use it, and your rights.', relatedSlugs: ['how-we-store-your-data','your-rights-as-a-customer'], featured: false, order: 1, updatedAt: '2025-01-01', tags: ['privacy','data','personal information','policy'] },
  { slug: 'how-we-store-your-data', category: 'legal-privacy-and-compliance', title: 'How we store and protect your data', description: 'DOT Mobile uses encryption in transit and at rest. Here is exactly how your data is protected.', relatedSlugs: ['privacy-policy-explained','account-security'], featured: false, order: 2, updatedAt: '2025-01-01', tags: ['data storage','security','encryption','GDPR','privacy'] },
  { slug: 'tio-and-complaints-process', category: 'legal-privacy-and-compliance', title: 'The TIO and our complaints process', description: 'If DOT Mobile cannot resolve your complaint, you can escalate to the Telecommunications Industry Ombudsman for free.', relatedSlugs: ['making-a-complaint','your-rights-as-a-customer'], featured: false, order: 3, updatedAt: '2025-01-01', tags: ['TIO','ombudsman','complaints','escalation'] },
  { slug: 'your-rights-as-a-customer', category: 'legal-privacy-and-compliance', title: 'Your rights as a DOT Mobile customer', description: 'Australian Consumer Law and the TCP Code give you important rights as a telecommunications customer.', relatedSlugs: ['making-a-complaint','tio-and-complaints-process','privacy-policy-explained'], featured: true, order: 4, updatedAt: '2025-01-01', tags: ['rights','consumer law','TCP Code','ACMA'] },
  { slug: 'making-a-complaint', category: 'legal-privacy-and-compliance', title: 'How to make a complaint', description: 'How to submit a formal complaint to DOT Mobile, what to expect, and how to escalate if needed.', relatedSlugs: ['tio-and-complaints-process','your-rights-as-a-customer'], featured: true, order: 5, updatedAt: '2025-01-01', tags: ['complaint','formal complaint','dispute','resolve'] },
]
