import type { SupportArticleMeta } from '@/types/support'

export const ARTICLES: SupportArticleMeta[] = [
  { slug: 'what-is-an-esim', category: 'esim-and-devices', title: 'What is an eSIM?', description: 'An eSIM is a digital SIM card built into your phone. No plastic, no shipping — activate instantly.', relatedSlugs: ['how-to-install-your-esim','device-compatibility','esim-only-explained'], featured: true, order: 1, updatedAt: '2025-01-01', tags: ['esim','digital sim','what is'] },
  { slug: 'how-to-install-your-esim', category: 'esim-and-devices', title: 'How to install your eSIM', description: 'Step-by-step guide to installing your DOT Mobile eSIM on any compatible device using the QR code.', relatedSlugs: ['install-esim-on-iphone','install-esim-on-android','esim-not-activating','device-compatibility'], featured: true, order: 2, updatedAt: '2025-01-01', tags: ['install','esim','qr code','setup','activation'] },
  { slug: 'device-compatibility', category: 'esim-and-devices', title: 'Device compatibility', description: 'Check whether your iPhone, Android, or Samsung device supports eSIM activation on DOT Mobile.', relatedSlugs: ['how-to-install-your-esim','what-is-an-esim','esim-not-activating'], featured: true, order: 3, updatedAt: '2025-01-01', tags: ['compatible devices','iphone','android','samsung','esim support'] },
  { slug: 'install-esim-on-iphone', category: 'esim-and-devices', title: 'How to install your eSIM on iPhone', description: 'Detailed steps for adding your DOT Mobile eSIM on iPhone XS and later models.', relatedSlugs: ['how-to-install-your-esim','device-compatibility','esim-not-activating'], featured: false, order: 4, updatedAt: '2025-01-01', tags: ['iphone','install','esim','apple','ios'] },
  { slug: 'install-esim-on-android', category: 'esim-and-devices', title: 'How to install your eSIM on Android', description: 'Generic Android eSIM installation steps for Google Pixel, OnePlus, Sony, and other Android devices.', relatedSlugs: ['how-to-install-your-esim','install-esim-on-samsung','esim-not-activating'], featured: false, order: 5, updatedAt: '2025-01-01', tags: ['android','install','esim','pixel','google'] },
  { slug: 'install-esim-on-samsung', category: 'esim-and-devices', title: 'How to install your eSIM on Samsung Galaxy', description: 'Step-by-step eSIM setup for Samsung Galaxy S and Z series devices.', relatedSlugs: ['install-esim-on-android','how-to-install-your-esim','esim-not-activating'], featured: false, order: 6, updatedAt: '2025-01-01', tags: ['samsung','galaxy','esim','android'] },
  { slug: 'how-many-esims-can-my-device-hold', category: 'esim-and-devices', title: 'How many eSIMs can my device hold?', description: 'Most modern devices support multiple eSIM profiles but can only have one active at a time.', relatedSlugs: ['what-is-an-esim','switching-devices','device-compatibility'], featured: false, order: 7, updatedAt: '2025-01-01', tags: ['multiple esim','device limit','esim profiles'] },
  { slug: 'switching-devices', category: 'esim-and-devices', title: 'Switching to a new device', description: 'How to move your DOT Mobile eSIM to a new phone when you upgrade your device.', relatedSlugs: ['how-to-install-your-esim','qr-code-expired-or-lost','device-compatibility'], featured: false, order: 8, updatedAt: '2025-01-01', tags: ['new phone','switching','transfer esim','upgrade'] },
  { slug: 'qr-code-expired-or-lost', category: 'esim-and-devices', title: 'My QR code has expired or I cannot find it', description: 'QR codes expire after 90 days. Here is how to request a new one from your account or by contacting support.', relatedSlugs: ['how-to-install-your-esim','esim-not-activating','resend-qr-code'], featured: false, order: 9, updatedAt: '2025-01-01', tags: ['qr code','expired','lost','resend'] },
]
