import type { SupportArticleMeta } from '@/types/support'

export const ARTICLES: SupportArticleMeta[] = [
  { slug: 'no-signal', category: 'troubleshooting-and-service-recovery', title: 'No signal or service', description: 'Step-by-step guide to diagnosing and fixing no signal on your DOT Mobile service.', relatedSlugs: ['check-coverage-in-your-area','device-compatibility','esim-showing-no-service'], featured: true, order: 1, updatedAt: '2025-01-01', tags: ['no signal','no service','offline','dead zone'] },
  { slug: 'cant-make-calls', category: 'troubleshooting-and-service-recovery', title: 'Cannot make or receive calls', description: 'Troubleshoot why calls are not working on your DOT Mobile service.', relatedSlugs: ['no-signal','esim-showing-no-service','cant-send-sms'], featured: false, order: 2, updatedAt: '2025-01-01', tags: ['calls','not working','phone calls','no audio'] },
  { slug: 'cant-send-sms', category: 'troubleshooting-and-service-recovery', title: 'Cannot send or receive SMS', description: 'Fix SMS delivery failures on DOT Mobile.', relatedSlugs: ['cant-make-calls','no-signal','esim-showing-no-service'], featured: false, order: 3, updatedAt: '2025-01-01', tags: ['sms','text','messages','not sending'] },
  { slug: 'slow-data', category: 'troubleshooting-and-service-recovery', title: 'Slow data or internet connection', description: 'Why your data might be slow and steps to improve speed on your DOT Mobile plan.', relatedSlugs: ['expected-speeds-by-plan','what-affects-signal-quality','what-happens-when-data-runs-out'], featured: false, order: 4, updatedAt: '2025-01-01', tags: ['slow','data speed','internet slow','throttled'] },
  { slug: 'esim-not-activating', category: 'troubleshooting-and-service-recovery', title: 'My eSIM is not activating', description: 'If your eSIM QR code scan is not working, follow these steps to resolve it.', relatedSlugs: ['how-to-install-your-esim','device-compatibility','qr-code-expired-or-lost'], featured: true, order: 5, updatedAt: '2025-01-01', tags: ['esim not working','activation failed','qr code','install error'] },
  { slug: 'esim-showing-no-service', category: 'troubleshooting-and-service-recovery', title: 'eSIM installed but showing no service', description: 'Your eSIM is installed but your phone shows no service. Here is how to fix it.', relatedSlugs: ['esim-not-activating','no-signal','device-compatibility'], featured: false, order: 6, updatedAt: '2025-01-01', tags: ['no service','esim installed','not connecting'] },
  { slug: 'resend-qr-code', category: 'troubleshooting-and-service-recovery', title: 'Resend my eSIM QR code', description: 'How to resend your eSIM activation email and QR code from your account.', relatedSlugs: ['qr-code-expired-or-lost','how-to-install-your-esim'], featured: false, order: 7, updatedAt: '2025-01-01', tags: ['resend','qr code','email','activation code'] },
  { slug: 'number-port-delayed', category: 'troubleshooting-and-service-recovery', title: 'My number port is taking longer than expected', description: 'Port delays are usually caused by your previous provider. Here is what to do and what to expect.', relatedSlugs: ['keep-your-number','why-number-transfer-can-fail'], featured: false, order: 8, updatedAt: '2025-01-01', tags: ['port delay','number transfer','slow port'] },
  { slug: 'account-suspended', category: 'troubleshooting-and-service-recovery', title: 'My account has been suspended', description: 'Accounts are suspended for non-payment or policy breaches. Here is how to reactivate your service.', relatedSlugs: ['payment-failed','how-billing-works','financial-hardship'], featured: false, order: 9, updatedAt: '2025-01-01', tags: ['suspended','account locked','no access'] },
  { slug: 'payment-failed', category: 'troubleshooting-and-service-recovery', title: 'My payment failed', description: 'What happens when a payment fails and how to update your details to restore your service.', relatedSlugs: ['account-suspended','update-payment-method','how-billing-works'], featured: false, order: 10, updatedAt: '2025-01-01', tags: ['payment failed','declined','card error'] },
]
