import type { SupportCategory } from '@/types/support'

export const SUPPORT_CATEGORIES: SupportCategory[] = [
  {
    slug: 'more-about-dot-mobile',
    title: 'More about DOT Mobile',
    description: 'Understand what DOT Mobile is, how it works, and who it is built for.',
    shortDescription: 'What DOT Mobile is and how it works.',
    icon: 'info', order: 1,
    featuredArticleSlugs: ['what-is-dot-mobile', 'what-network-do-we-use'],
    relatedCategorySlugs: ['sign-up-and-activation', 'esim-and-devices'],
  },
  {
    slug: 'sign-up-and-activation',
    title: 'Sign up and Activation',
    description: 'Everything you need to get your DOT Mobile service set up from choosing a plan to your first connection.',
    shortDescription: 'From sign-up to first connection.',
    icon: 'user-plus', order: 2,
    featuredArticleSlugs: ['how-to-sign-up', 'keep-your-number'],
    relatedCategorySlugs: ['esim-and-devices', 'troubleshooting-and-service-recovery'],
  },
  {
    slug: 'esim-and-devices',
    title: 'eSIM and Devices',
    description: 'How to install your eSIM, check device compatibility, and manage your digital SIM across devices.',
    shortDescription: 'eSIM installation and device compatibility.',
    icon: 'phone', order: 3,
    featuredArticleSlugs: ['how-to-install-your-esim', 'device-compatibility'],
    relatedCategorySlugs: ['sign-up-and-activation', 'troubleshooting-and-service-recovery'],
  },
  {
    slug: 'plans-billing-and-payments',
    title: 'Plans, Billing and Payments',
    description: 'How billing works, what is included in each plan, how to change plans, and how to manage your payments.',
    shortDescription: 'Billing, payments, and plan changes.',
    icon: 'credit-card', order: 4,
    featuredArticleSlugs: ['how-billing-works', 'how-to-cancel'],
    relatedCategorySlugs: ['troubleshooting-and-service-recovery', 'legal-privacy-and-compliance'],
  },
  {
    slug: 'network-coverage-and-speeds',
    title: 'Network, Coverage and Speeds',
    description: 'Learn about the Telstra 5G network, check coverage in your area, and understand what speeds to expect.',
    shortDescription: 'Coverage, network, and speed information.',
    icon: 'signal', order: 5,
    featuredArticleSlugs: ['what-network-do-we-use', 'expected-speeds-by-plan'],
    relatedCategorySlugs: ['troubleshooting-and-service-recovery', 'more-about-dot-mobile'],
  },
  {
    slug: 'troubleshooting-and-service-recovery',
    title: 'Troubleshooting and Service Recovery',
    description: 'Diagnose and fix common service issues from no signal to eSIM activation failures.',
    shortDescription: 'Fix common service issues.',
    icon: 'wrench', order: 6,
    featuredArticleSlugs: ['no-signal', 'esim-not-activating'],
    relatedCategorySlugs: ['esim-and-devices', 'network-coverage-and-speeds'],
  },
  {
    slug: 'security-fraud-and-scam-protection',
    title: 'Security, Fraud and Scam Protection',
    description: 'How to protect your account, identify scam messages, and report fraudulent activity.',
    shortDescription: 'Account security and fraud protection.',
    icon: 'shield', order: 7,
    featuredArticleSlugs: ['scam-messages-and-phishing', 'account-security'],
    relatedCategorySlugs: ['legal-privacy-and-compliance'],
  },
  {
    slug: 'international-roaming-and-add-ons',
    title: 'International Roaming and Add-ons',
    description: 'How to enable roaming, which countries are supported, and how to purchase data and calling add-ons.',
    shortDescription: 'Roaming and add-on services.',
    icon: 'globe', order: 8,
    featuredArticleSlugs: ['how-roaming-works', 'roaming-countries'],
    relatedCategorySlugs: ['plans-billing-and-payments'],
  },
  {
    slug: 'legal-privacy-and-compliance',
    title: 'Legal, Privacy and Compliance',
    description: 'Plain-language explanations of your rights, our policies, and how to make a complaint.',
    shortDescription: 'Your rights and how to make a complaint.',
    icon: 'document', order: 9,
    featuredArticleSlugs: ['your-rights-as-a-customer', 'making-a-complaint'],
    relatedCategorySlugs: ['plans-billing-and-payments', 'security-fraud-and-scam-protection'],
  },
]
