import type { SupportArticleMeta } from '@/types/support'

export const ARTICLES: SupportArticleMeta[] = [
  { slug: 'what-is-dot-mobile', category: 'more-about-dot-mobile', title: 'What is DOT Mobile?', description: 'DOT Mobile is an Australian eSIM-only mobile carrier built for digital-first customers. No stores, no plastic SIM.', relatedSlugs: ['what-network-do-we-use','esim-only-explained','how-dot-mobile-works'], featured: true, order: 1, updatedAt: '2025-01-01', tags: ['what is','about','dot mobile','overview'] },
  { slug: 'who-is-dot-mobile-for', category: 'more-about-dot-mobile', title: 'Who is DOT Mobile for?', description: 'DOT Mobile is built for anyone who wants a simple, digital, contract-free mobile service — especially Gen Z, diaspora communities, and remote workers.', relatedSlugs: ['what-is-dot-mobile','what-network-do-we-use'], featured: false, order: 2, updatedAt: '2025-01-01', tags: ['target audience','who','for whom','suitable'] },
  { slug: 'what-network-do-we-use', category: 'more-about-dot-mobile', title: 'What network does DOT Mobile use?', description: 'DOT Mobile operates on the Telstra wholesale mobile network — 4G and 5G across 98.5% of Australia.', relatedSlugs: ['what-is-dot-mobile','check-coverage-in-your-area','4g-vs-5g'], featured: true, order: 3, updatedAt: '2025-01-01', tags: ['network','telstra','coverage','5G'] },
  { slug: 'esim-only-explained', category: 'more-about-dot-mobile', title: 'Why DOT Mobile is eSIM-only', description: 'We chose eSIM because it is faster, greener, and more secure than a physical SIM. No waiting, no plastic.', relatedSlugs: ['what-is-an-esim','how-to-install-your-esim','device-compatibility'], featured: false, order: 4, updatedAt: '2025-01-01', tags: ['esim only','why esim','digital sim','no physical sim'] },
  { slug: 'how-dot-mobile-works', category: 'more-about-dot-mobile', title: 'How DOT Mobile works', description: 'Choose a plan, verify your identity, pay, scan your QR code — you are live in minutes. No store visit required.', relatedSlugs: ['how-to-sign-up','what-happens-after-payment','how-to-install-your-esim'], featured: false, order: 5, updatedAt: '2025-01-01', tags: ['how it works','process','sign up','overview'] },
]
