import type { SupportArticleMeta } from '@/types/support'

export const ARTICLES: SupportArticleMeta[] = [
  { slug: 'how-to-sign-up', category: 'sign-up-and-activation', title: 'How to sign up for DOT Mobile', description: 'A step-by-step walkthrough of the sign-up process, from choosing a plan to your first connection.', relatedSlugs: ['what-you-need-before-signing-up','how-identity-verification-works','how-to-install-your-esim','device-compatibility'], featured: true, order: 1, updatedAt: '2025-01-01', tags: ['sign up','getting started','new customer','activation'] },
  { slug: 'what-you-need-before-signing-up', category: 'sign-up-and-activation', title: 'What you need before signing up', description: 'Make sure you have everything ready before you start — device, ID, and payment details.', relatedSlugs: ['how-to-sign-up','device-compatibility','how-identity-verification-works'], featured: false, order: 2, updatedAt: '2025-01-01', tags: ['requirements','checklist','getting started'] },
  { slug: 'how-identity-verification-works', category: 'sign-up-and-activation', title: 'How identity verification works', description: 'Why we verify your identity, what documents are accepted, and how the process works.', relatedSlugs: ['how-to-sign-up','account-security'], featured: false, order: 3, updatedAt: '2025-01-01', tags: ['identity','verification','ID','KYC'] },
  { slug: 'keep-your-number', category: 'sign-up-and-activation', title: 'How to keep your existing mobile number', description: 'Transfer your current mobile number to DOT Mobile during sign-up. Here is exactly how it works and what to expect.', relatedSlugs: ['why-number-transfer-can-fail','how-long-does-activation-take','number-port-delayed'], featured: true, order: 4, updatedAt: '2025-01-01', tags: ['number port','keep number','transfer','MNP'] },
  { slug: 'get-a-new-number', category: 'sign-up-and-activation', title: 'Get a new mobile number', description: 'Choosing to receive a new number instead of porting? Here is what happens and how numbers are assigned.', relatedSlugs: ['how-to-sign-up','keep-your-number'], featured: false, order: 5, updatedAt: '2025-01-01', tags: ['new number','phone number'] },
  { slug: 'why-number-transfer-can-fail', category: 'sign-up-and-activation', title: 'Why a number transfer can fail', description: 'Common reasons a port-in fails and what to do if yours does not complete on time.', relatedSlugs: ['keep-your-number','number-port-delayed','account-suspended'], featured: false, order: 6, updatedAt: '2025-01-01', tags: ['port fail','number transfer','troubleshooting'] },
  { slug: 'how-long-does-activation-take', category: 'sign-up-and-activation', title: 'How long does activation take?', description: 'eSIM delivery is usually within 5 minutes of payment. Number porting takes 1 to 2 business days.', relatedSlugs: ['how-to-sign-up','what-happens-after-payment','esim-not-activating'], featured: false, order: 7, updatedAt: '2025-01-01', tags: ['activation time','how long','wait time'] },
  { slug: 'what-happens-after-payment', category: 'sign-up-and-activation', title: 'What happens after payment', description: 'From payment confirmation to live service — what happens behind the scenes after you complete checkout.', relatedSlugs: ['how-to-install-your-esim','how-long-does-activation-take','esim-not-activating'], featured: false, order: 8, updatedAt: '2025-01-01', tags: ['after payment','next steps','activation'] },
]
