import type { SupportArticleMeta } from '@/types/support'

export const ARTICLES: SupportArticleMeta[] = [
  { slug: 'what-network-do-we-use', category: 'network-coverage-and-speeds', title: 'What network does DOT Mobile use?', description: 'DOT Mobile operates on the Telstra wholesale mobile network — 4G and 5G across Australia.', relatedSlugs: ['4g-vs-5g','expected-speeds-by-plan','check-coverage-in-your-area'], featured: true, order: 1, updatedAt: '2025-01-01', tags: ['network','telstra','infrastructure','wholesale'] },
  { slug: '4g-vs-5g', category: 'network-coverage-and-speeds', title: '4G vs 5G — what is the difference?', description: 'How 4G and 5G differ, which plans get 5G, and what to expect if 5G is not in your area.', relatedSlugs: ['what-network-do-we-use','expected-speeds-by-plan'], featured: false, order: 2, updatedAt: '2025-01-01', tags: ['4g','5g','network generation','speed'] },
  { slug: 'check-coverage-in-your-area', category: 'network-coverage-and-speeds', title: 'How to check coverage in your area', description: 'Use the Telstra coverage checker for the most accurate coverage information at your address.', relatedSlugs: ['what-network-do-we-use','no-signal','coverage-in-regional-areas'], featured: false, order: 3, updatedAt: '2025-01-01', tags: ['coverage check','coverage map','my area'] },
  { slug: 'expected-speeds-by-plan', category: 'network-coverage-and-speeds', title: 'Expected speeds by plan', description: 'Starter goes up to 100 Mbps. Core and Unlimited up to 150 Mbps. Ultra gets priority 5G access.', relatedSlugs: ['what-network-do-we-use','what-affects-signal-quality','slow-data'], featured: true, order: 4, updatedAt: '2025-01-01', tags: ['speed','mbps','download','plan speed'] },
  { slug: 'what-affects-signal-quality', category: 'network-coverage-and-speeds', title: 'What affects signal quality?', description: 'Location, device, building materials, network congestion, and distance from towers all affect your signal.', relatedSlugs: ['expected-speeds-by-plan','no-signal','slow-data'], featured: false, order: 5, updatedAt: '2025-01-01', tags: ['signal','reception','interference','weak signal'] },
  { slug: 'network-outages', category: 'network-coverage-and-speeds', title: 'Network outages', description: 'What to do if there is a network outage, how we communicate outages, and what compensation may apply.', relatedSlugs: ['no-signal','check-coverage-in-your-area'], featured: false, order: 6, updatedAt: '2025-01-01', tags: ['outage','down','service disruption'] },
  { slug: 'coverage-in-regional-areas', category: 'network-coverage-and-speeds', title: 'Coverage in regional and remote areas', description: 'Telstra wholesale coverage reaches most of regional Australia. Here is what to expect outside metro areas.', relatedSlugs: ['what-network-do-we-use','check-coverage-in-your-area','4g-vs-5g'], featured: false, order: 7, updatedAt: '2025-01-01', tags: ['regional','rural','remote','outback','FIFO'] },
]
