import type { PlanDefinition, FeatureRow } from '@/types/plans'

export const PLANS: PlanDefinition[] = [
  {
    key: 'starter',
    name: 'Starter',
    tagline: 'For lighter use.',
    description: 'Enough for everyday browsing, social, and calls.',
    data: '25 GB',
    speed: 'Up to 100 Mbps',
    speedNote: null,
    price: 35,
    featured: false,
    dark: false,
    ctaLabel: 'Select',
    stripePriceId: process.env.STRIPE_PRICE_STARTER ?? '',
    inclusions: [
      'Unlimited standard national calls',
      'Unlimited standard national SMS',
      'Mobile hotspot',
      'Voicemail',
      'eSIM-only activation',
    ],
  },
  {
    key: 'core',
    name: 'Core',
    tagline: 'Most popular.',
    description: 'Streaming, social, and work — all covered.',
    data: '50 GB',
    speed: 'Up to 150 Mbps',
    speedNote: null,
    price: 42,
    featured: true,
    dark: false,
    ctaLabel: 'Continue',
    stripePriceId: process.env.STRIPE_PRICE_CORE ?? '',
    inclusions: [
      'Unlimited standard national calls',
      'Unlimited standard national SMS',
      'Mobile hotspot',
      'Voicemail',
      'eSIM-only activation',
    ],
  },
  {
    key: 'unlimited',
    name: 'Unlimited',
    tagline: 'For heavy users.',
    description: 'No data cap. Fast speeds. Fair use applies.',
    data: 'No cap',
    speed: 'Up to 150 Mbps',
    speedNote: 'Fair use applies',
    price: 55,
    featured: false,
    dark: false,
    ctaLabel: 'Upgrade',
    stripePriceId: process.env.STRIPE_PRICE_UNLIMITED ?? '',
    inclusions: [
      'Unlimited standard national calls',
      'Unlimited standard national SMS',
      'Mobile hotspot',
      'Voicemail',
      'eSIM-only activation',
      'Roaming add-ons available',
    ],
  },
  {
    key: 'ultra',
    name: 'Ultra',
    tagline: 'Priority experience.',
    description: 'Priority network access. No data cap.',
    data: 'No cap',
    speed: 'Priority 5G access',
    speedNote: 'Highest network priority',
    price: 70,
    featured: false,
    dark: true,
    ctaLabel: 'Go Ultra',
    stripePriceId: process.env.STRIPE_PRICE_ULTRA ?? '',
    inclusions: [
      'Unlimited standard national calls',
      'Unlimited standard national SMS',
      'Mobile hotspot',
      'Voicemail',
      'eSIM-only activation',
      'Roaming add-ons available',
      'Priority network access',
    ],
  },
]

export const PLAN_FEATURES: FeatureRow[] = [
  { feature: 'Monthly price',     starter: '$35',      core: '$42',      unlimited: '$55',      ultra: '$70' },
  { feature: 'Data',              starter: '25 GB',    core: '50 GB',    unlimited: 'No cap',   ultra: 'No cap' },
  { feature: 'Download speed',    starter: '100 Mbps', core: '150 Mbps', unlimited: '150 Mbps', ultra: 'Priority 5G' },
  { feature: 'Calls and SMS',     starter: 'Unlimited',core: 'Unlimited',unlimited: 'Unlimited',ultra: 'Unlimited' },
  { feature: 'Mobile hotspot',    starter: true,       core: true,       unlimited: true,       ultra: true },
  { feature: 'eSIM activation',   starter: true,       core: true,       unlimited: true,       ultra: true },
  { feature: 'Roaming add-ons',   starter: false,      core: false,      unlimited: true,       ultra: true },
  { feature: 'Network priority',  starter: false,      core: false,      unlimited: false,      ultra: true },
  { feature: 'Contract',          starter: 'None',     core: 'None',     unlimited: 'None',     ultra: 'None' },
  { feature: 'Exit fee',          starter: '$0',       core: '$0',       unlimited: '$0',       ultra: '$0' },
]

export function getPlan(key: string): PlanDefinition {
  return PLANS.find(p => p.key === key) ?? PLANS[1]
}
