import type { SupportArticleMeta } from '@/types/support'

export const ARTICLES: SupportArticleMeta[] = [
  { slug: 'how-billing-works', category: 'plans-billing-and-payments', title: 'How billing works', description: 'Your plan renews monthly on the same date. Your card is charged automatically. Here is everything you need to know.', relatedSlugs: ['when-am-i-charged','invoices-and-receipts','update-payment-method'], featured: true, order: 1, updatedAt: '2025-01-01', tags: ['billing','payment','invoice','renewal'] },
  { slug: 'when-am-i-charged', category: 'plans-billing-and-payments', title: 'When am I charged?', description: 'You are charged on your renewal date each month — the same calendar date as your original activation.', relatedSlugs: ['how-billing-works','invoices-and-receipts'], featured: false, order: 2, updatedAt: '2025-01-01', tags: ['charge','payment date','renewal'] },
  { slug: 'how-to-change-your-plan', category: 'plans-billing-and-payments', title: 'How to change your plan', description: 'You can upgrade or downgrade your plan any time from your account. Changes take effect at your next renewal date.', relatedSlugs: ['how-billing-works','how-to-cancel'], featured: false, order: 3, updatedAt: '2025-01-01', tags: ['change plan','upgrade','downgrade'] },
  { slug: 'what-happens-when-data-runs-out', category: 'plans-billing-and-payments', title: 'What happens when my data runs out?', description: 'On Starter and Core, your speed drops to 1 Mbps for the rest of the billing cycle. You are never charged extra.', relatedSlugs: ['how-billing-works','data-add-ons','how-to-change-your-plan'], featured: false, order: 4, updatedAt: '2025-01-01', tags: ['data limit','throttle','excess data','data cap'] },
  { slug: 'data-add-ons', category: 'plans-billing-and-payments', title: 'Data add-ons', description: 'Purchase a one-off data top-up to restore full speeds on Starter or Core plans mid-cycle.', relatedSlugs: ['what-happens-when-data-runs-out','how-billing-works'], featured: false, order: 5, updatedAt: '2025-01-01', tags: ['data top-up','add-on','extra data'] },
  { slug: 'how-to-cancel', category: 'plans-billing-and-payments', title: 'How to cancel your subscription', description: 'Cancel anytime from your account with no fees. Service stays active until the end of your current billing period.', relatedSlugs: ['how-billing-works','refunds-and-credits'], featured: true, order: 6, updatedAt: '2025-01-01', tags: ['cancel','cancellation','end service','exit'] },
  { slug: 'refunds-and-credits', category: 'plans-billing-and-payments', title: 'Refunds and credits', description: 'When refunds apply, how credits work, and what to do if you have been charged incorrectly.', relatedSlugs: ['how-to-cancel','how-billing-works','financial-hardship'], featured: false, order: 7, updatedAt: '2025-01-01', tags: ['refund','credit','billing error'] },
  { slug: 'update-payment-method', category: 'plans-billing-and-payments', title: 'Update your payment method', description: 'How to change your card details from your account before your next renewal to avoid service suspension.', relatedSlugs: ['how-billing-works','when-am-i-charged'], featured: false, order: 8, updatedAt: '2025-01-01', tags: ['payment method','card','update card'] },
  { slug: 'invoices-and-receipts', category: 'plans-billing-and-payments', title: 'Invoices and receipts', description: 'Where to find your invoices, how to download them, and what they include.', relatedSlugs: ['how-billing-works','when-am-i-charged'], featured: false, order: 9, updatedAt: '2025-01-01', tags: ['invoice','receipt','tax invoice','GST'] },
  { slug: 'financial-hardship', category: 'plans-billing-and-payments', title: 'Financial hardship support', description: 'If you are struggling to pay your bill, contact us before your service is suspended. We can help.', relatedSlugs: ['how-to-cancel','refunds-and-credits'], featured: false, order: 10, updatedAt: '2025-01-01', tags: ['hardship','financial difficulty','payment plan'] },
]
