import type { SupportArticleMeta } from '@/types/support'

export const ARTICLES: SupportArticleMeta[] = [
  { slug: 'scam-messages-and-phishing', category: 'security-fraud-and-scam-protection', title: 'Scam messages and phishing', description: 'How to identify scam SMS and emails pretending to be from DOT Mobile, and what to do if you receive one.', relatedSlugs: ['suspicious-dot-mobile-messages','account-security','report-fraud'], featured: true, order: 1, updatedAt: '2025-01-01', tags: ['scam','phishing','fake sms','fraud'] },
  { slug: 'suspicious-dot-mobile-messages', category: 'security-fraud-and-scam-protection', title: 'Suspicious messages claiming to be from DOT Mobile', description: 'DOT Mobile will never ask for your password or payment details via SMS. Here is how to tell real from fake.', relatedSlugs: ['scam-messages-and-phishing','report-fraud'], featured: false, order: 2, updatedAt: '2025-01-01', tags: ['fake message','impersonation','scam sms'] },
  { slug: 'account-security', category: 'security-fraud-and-scam-protection', title: 'Account security best practices', description: 'How to keep your DOT Mobile account secure, including strong passwords, 2FA, and suspicious activity.', relatedSlugs: ['two-factor-authentication','sim-swap-fraud','scam-messages-and-phishing'], featured: true, order: 3, updatedAt: '2025-01-01', tags: ['security','password','2FA','account protection'] },
  { slug: 'sim-swap-fraud', category: 'security-fraud-and-scam-protection', title: 'SIM swap fraud', description: 'What SIM swap fraud is, how we protect against it, and what to do if you suspect your number has been stolen.', relatedSlugs: ['account-security','report-fraud','two-factor-authentication'], featured: false, order: 4, updatedAt: '2025-01-01', tags: ['sim swap','number hijack','account takeover'] },
  { slug: 'report-fraud', category: 'security-fraud-and-scam-protection', title: 'How to report fraud', description: 'Steps to report suspected fraud to DOT Mobile, Australian authorities, and Scamwatch.', relatedSlugs: ['scam-messages-and-phishing','account-security','sim-swap-fraud'], featured: false, order: 5, updatedAt: '2025-01-01', tags: ['report','fraud','scamwatch','police'] },
  { slug: 'two-factor-authentication', category: 'security-fraud-and-scam-protection', title: 'Two-factor authentication (2FA)', description: 'How to enable 2FA on your DOT Mobile account and why it is the single most effective account security measure.', relatedSlugs: ['account-security','sim-swap-fraud'], featured: false, order: 6, updatedAt: '2025-01-01', tags: ['2FA','two factor','MFA','authenticator'] },
]
