import type { SupportArticleMeta } from '@/types/support'

export const ARTICLES: SupportArticleMeta[] = [
  { slug: 'how-roaming-works', category: 'international-roaming-and-add-ons', title: 'How roaming works', description: 'International roaming on DOT Mobile is available as an optional add-on on Unlimited and Ultra plans.', relatedSlugs: ['roaming-countries','enable-roaming','international-calling'], featured: true, order: 1, updatedAt: '2025-01-01', tags: ['roaming','international','travel','overseas'] },
  { slug: 'roaming-countries', category: 'international-roaming-and-add-ons', title: 'Supported roaming countries', description: 'A list of countries where DOT Mobile international roaming add-ons are available.', relatedSlugs: ['how-roaming-works','enable-roaming'], featured: true, order: 2, updatedAt: '2025-01-01', tags: ['roaming countries','destinations','travel countries'] },
  { slug: 'enable-roaming', category: 'international-roaming-and-add-ons', title: 'How to enable roaming', description: 'How to purchase and activate a DOT Mobile international roaming add-on before you travel.', relatedSlugs: ['how-roaming-works','roaming-countries'], featured: false, order: 3, updatedAt: '2025-01-01', tags: ['enable roaming','activate roaming','travel'] },
  { slug: 'international-calling', category: 'international-roaming-and-add-ons', title: 'International calling', description: 'How to call international numbers from Australia on DOT Mobile, and available international calling add-ons.', relatedSlugs: ['how-roaming-works','data-add-ons'], featured: false, order: 4, updatedAt: '2025-01-01', tags: ['international calls','overseas calls','IDD'] },
  { slug: 'data-add-ons-roaming', category: 'international-roaming-and-add-ons', title: 'Data add-ons for travel', description: 'Purchase roaming data packs for use in supported international destinations.', relatedSlugs: ['how-roaming-works','enable-roaming'], featured: false, order: 5, updatedAt: '2025-01-01', tags: ['data pack','roaming data','travel data'] },
]
